#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
require 5.6.0;
use strict;
use warnings;
use Thrift;

package Facebook::FB303::fb_status;
use constant DEAD => 0;
use constant STARTING => 1;
use constant ALIVE => 2;
use constant STOPPING => 3;
use constant STOPPED => 4;
use constant WARNING => 5;
1;
